services:
    formundzeichen_contao-cookie-consent-bundle.listener.hooks:
        class: Formundzeichen\ContaoCookieConsentBundle\EventListener\TemplateListener
        public: true
        arguments:
            - "@contao.framework"